# Usage NumPy 

## Setup

Before we begin, make sure you have NumPy installed. If not, you can install it by running the following command:

In [ ]:
!pip install numpy

#### let's explore a basic example using NumPy!

import the numpy as np, so that we can call everywhere as np

In [1]:
import numpy as np


#### Basic NumPy Operations

In [2]:
# Create NumPy arrays
array_a = np.array([1, 2, 3, 4, 5])
array_b = np.array([2, 4, 6, 8, 10])
print("Array A:", array_a)
print("Array B:", array_b)

# Element-wise addition
result_addition = array_a + array_b
print("Array A + Array B:", result_addition)

# Element-wise multiplication
result_multiplication = array_a * array_b
print("Array A * Array B:", result_multiplication)

# Element-wise square root
result_sqrt = np.sqrt(array_a)
print("Square Root of Array A:", result_sqrt)


Array A: [1 2 3 4 5]
Array B: [ 2  4  6  8 10]
Array A + Array B: [ 3  6  9 12 15]
Array A * Array B: [ 2  8 18 32 50]
Square Root of Array A: [1.         1.41421356 1.73205081 2.         2.23606798]


### Matrix Operations with NumPy


In [3]:
# Create two matrices with the help of numpy
matrix_a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print("Matrix A:\n", matrix_a)
print("Matrix B:\n", matrix_b)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [4]:
# Matrix addition
result_addition = matrix_a + matrix_b
print("Matrix A + Matrix B:\n", result_addition)

Matrix A + Matrix B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [5]:
# Matrix multiplication
result_multiplication = np.dot(matrix_a, matrix_b)
print("Matrix A * Matrix B:\n", result_multiplication)


Matrix A * Matrix B:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [6]:
# Transpose of a matrix
transpose_a = np.transpose(matrix_a)
transpose_b = np.transpose(matrix_b)
print("Transpose of Matrix A:\n", transpose_a)
print("Transpose of Matrix B:\n", transpose_b)

Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of Matrix B:
 [[9 6 3]
 [8 5 2]
 [7 4 1]]
